# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(1064, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setStyleSheet("background-color: rgba(53, 132, 228,70);")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("/* Style par défaut du bouton */\n"
"\n"
"QPushButton {\n"
"color: rgb(198, 198, 255);\n"
"    background-color: rgb(222, 221, 218);\n"
"    border-radius: 5px;      /* C\'est ici que l\'arrondi se joue */\n"
"    padding: 10px 0;\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid blue;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"/* Effet au survol de la souris (Hover) */\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color : blue;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("/* Style par défaut du bouton */\n"
"\n"
"QPushButton {\n"
"color: rgb(198, 198, 255);\n"
"    background-color: rgb(222, 221, 218);\n"
"    border-radius: 5px;      /* C\'est ici que l\'arrondi se joue */\n"
"    padding: 10px 0;\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid blue;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"/* Effet au survol de la souris (Hover) */\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color : blue;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("/* Style par défaut du bouton */\n"
"\n"
"QPushButton {\n"
"color: rgb(198, 198, 255);\n"
"    background-color: rgb(222, 221, 218);\n"
"    border-radius: 5px;      /* C\'est ici que l\'arrondi se joue */\n"
"    padding: 10px 0;\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid blue;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"/* Effet au survol de la souris (Hover) */\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color : blue;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setStyleSheet("border-radius : 7px;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.operations = QtWidgets.QWidget()
        self.operations.setObjectName("operations")
        self.comboBox = QtWidgets.QComboBox(self.operations)
        self.comboBox.setGeometry(QtCore.QRect(190, 100, 371, 41))
        self.comboBox.setStyleSheet("padding:5px;\n"
"font-size: 14px;\n"
"color: black;\n"
"font-weight : bold;\n"
"border-radius : 3px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(self.operations)
        self.label.setGeometry(QtCore.QRect(290, 60, 181, 31))
        self.label.setStyleSheet("font: italic 12pt \"MS Sans Serif\";\n"
"padding: 5px;\n"
"\n"
"background-color: rgba(255, 255, 255, 40);")
        self.label.setObjectName("label")
        self.pushButton_4 = QtWidgets.QPushButton(self.operations)
        self.pushButton_4.setGeometry(QtCore.QRect(250, 410, 291, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("/* Style par défaut du bouton */\n"
"QPushButton {    \n"
"    background-color: rgb(55, 144, 138);\n"
"    color: white;\n"
"    border-radius: 4px;      /* C\'est ici que l\'arrondi se joue */\n"
"    border: 3px solid #52c3c5;\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"/* Effet au survol de la souris (Hover) */\n"
"QPushButton:hover {\n"
"    background-color: #52c3c5;\n"
"    font-weight : bold;\n"
"}\n"
"\n"
"/* Effet quand on clique (Pressed) */\n"
"QPushButton:pressed {\n"
"    background-color: blue;\n"
"    padding-left: 7px; /* Petit effet de mouvement */\n"
"    padding-top: 7px;\n"
"}background-color: rgb(85, 0, 255);\n"
"font: italic 15pt \"MS Sans Serif\";\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.zoneChamps = QtWidgets.QWidget(self.operations)
        self.zoneChamps.setGeometry(QtCore.QRect(10, 240, 761, 47))
        self.zoneChamps.setStyleSheet("border-radius: 10px;\n"
"padding: 10px 20px;\n"
"background-color: rgb(255, 255, 255,70);")
        self.zoneChamps.setObjectName("zoneChamps")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.zoneChamps)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.zoneChamps)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: italic 12pt \"MS Sans Serif\";\n"
"padding: 5px;\n"
"color: rgb(50, 50, 50);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.stackedWidget.addWidget(self.operations)
        self.journal = QtWidgets.QWidget()
        self.journal.setObjectName("journal")
        self.gridLayout = QtWidgets.QGridLayout(self.journal)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtWidgets.QWidget(self.journal)
        self.widget_2.setStyleSheet("border-radius: 10px;\n"
"border-color: rgb(94, 92, 100);")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.dateDebut = QtWidgets.QDateEdit(self.widget_2)
        self.dateDebut.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"/*width : 150px; */\n"
"color: rgb(0, 0, 0);\n"
"\n"
"")
        self.dateDebut.setCalendarPopup(True)
        self.dateDebut.setObjectName("dateDebut")
        self.horizontalLayout.addWidget(self.dateDebut)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.dateFin = QtWidgets.QDateEdit(self.widget_2)
        self.dateFin.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"/*width : 150px;*/\n"
"color: rgb(0, 0, 0);\n"
"")
        self.dateFin.setCalendarPopup(True)
        self.dateFin.setObjectName("dateFin")
        self.horizontalLayout.addWidget(self.dateFin)
        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 3)
        self.btnFiltrer = QtWidgets.QPushButton(self.journal)
        self.btnFiltrer.setStyleSheet("/* Style par défaut du bouton */\n"
"QPushButton {\n"
"    background-color: rgb(20, 92, 159);\n"
"    color: white;\n"
"    border: 3px solid #146edd;\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"    border-radius : 3px;\n"
"}\n"
"\n"
"/* Effet au survol de la souris (Hover) */\n"
"QPushButton:hover {\n"
"    background-color: rgb(20, 110, 221);\n"
"    font-weight : bold;\n"
"}\n"
"\n"
"font: italic 15pt \"MS Sans Serif\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.btnFiltrer.setObjectName("btnFiltrer")
        self.gridLayout.addWidget(self.btnFiltrer, 1, 0, 1, 1)
        self.btnActualiser = QtWidgets.QPushButton(self.journal)
        self.btnActualiser.setStyleSheet("/* Style par défaut du bouton */\n"
"QPushButton {    \n"
"    background-color: rgb(55, 144, 138);\n"
"    color: white;\n"
"    border-radius: 4px;      /* C\'est ici que l\'arrondi se joue */\n"
"    border: 3px solid #52c3c5;\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"/* Effet au survol de la souris (Hover) */\n"
"QPushButton:hover {\n"
"    background-color: #52c3c5;\n"
"    font-weight : bold;\n"
"}\n"
"\n"
"/* Effet quand on clique (Pressed) */\n"
"QPushButton:pressed {\n"
"    background-color: blue;\n"
"    padding-left: 7px; /* Petit effet de mouvement */\n"
"    padding-top: 7px;\n"
"}background-color: rgb(85, 0, 255);\n"
"font: italic 15pt \"MS Sans Serif\";\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.btnActualiser.setObjectName("btnActualiser")
        self.gridLayout.addWidget(self.btnActualiser, 1, 1, 1, 1)
        self.pushButton_export = QtWidgets.QPushButton(self.journal)
        self.pushButton_export.setStyleSheet("/* Style par défaut du bouton */\n"
"QPushButton {\n"
"    background-color: rgb(0, 120, 18);\n"
"    color: white;\n"
"    border-radius: 8px;      /* C\'est ici que l\'arrondi se joue */\n"
"    border: 3px solid #11af00;\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"/* Effet au survol de la souris (Hover) */\n"
"QPushButton:hover {\n"
"    background-color: rgb(17, 175, 0);\n"
"    font-weight : bold;\n"
"}\n"
"\n"
"/* Effet quand on clique (Pressed) */\n"
"QPushButton:pressed {\n"
"    background-color: blue;\n"
"    padding-left: 7px; /* Petit effet de mouvement */\n"
"    padding-top: 7px;\n"
"}background-color: rgb(85, 0, 255);\n"
"font: italic 15pt \"MS Sans Serif\";\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.pushButton_export.setObjectName("pushButton_export")
        self.gridLayout.addWidget(self.pushButton_export, 1, 2, 1, 1)
        self.tableView = QtWidgets.QTableView(self.journal)
        self.tableView.setStyleSheet("font-weight : bold;\n"
"border-radius : 6px;")
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 2, 0, 1, 3)
        self.stackedWidget.addWidget(self.journal)
        self.grandLivre = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grandLivre.sizePolicy().hasHeightForWidth())
        self.grandLivre.setSizePolicy(sizePolicy)
        self.grandLivre.setObjectName("grandLivre")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.grandLivre)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(self.grandLivre)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.grandLivre)
        self.plainTextEdit.setStyleSheet("font-weight : bold;\n"
"border-radius : 6px;")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_3.addWidget(self.plainTextEdit, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.grandLivre)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Logiciel Comptabilité"))
        self.pushButton.setText(_translate("MainWindow", "Opérations"))
        self.pushButton_2.setText(_translate("MainWindow", "Journal"))
        self.pushButton_3.setText(_translate("MainWindow", "Grand-livre"))
        self.label.setText(_translate("MainWindow", "Choisir une opération"))
        self.pushButton_4.setText(_translate("MainWindow", "Enregistrer l\'opération"))
        self.label_2.setText(_translate("MainWindow", "Champ (s) à completer"))
        self.label_3.setText(_translate("MainWindow", "Date début"))
        self.label_4.setText(_translate("MainWindow", "Date fin"))
        self.btnFiltrer.setText(_translate("MainWindow", "Filtrer"))
        self.btnActualiser.setText(_translate("MainWindow", "Actualiser"))
        self.pushButton_export.setText(_translate("MainWindow", "Exporter ver PDF"))
        self.label_6.setText(_translate("MainWindow", "Grand Livre"))
